name: Build Rust CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]

env:
  RUST_VERSION: 1.79

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Caching
        uses: Swatinem/rust-cache@v2

      - name: Run cargo build
        run: |
          cargo build
      
      - name: Run cargo clippy
        run: |
          cargo clippy --all-targets --all-features -- -D warnings

      - name: Run cargo fmt
        run: |
          cargo fmt --all -- --check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
    
      - name: Caching
        uses: Swatinem/rust-cache@v2
          
      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          foundryup

      - name: Run anvil with deployed contracts
        run: |
          chmod +x contracts/anvil/load_state.sh
          ./contracts/anvil/load_state.sh
          ls contracts/anvil/state.json

      - name: Run tests
        run: cargo test --workspace
